In [5]:
import numpy as np
x = np.array([3, 1, 2])
print(x)
print(type(x))
print(type([3, 1, 2]))

[3 1 2]
<class 'numpy.ndarray'>
<class 'list'>


In [9]:
c = [[1], [1,2]]
d = np.array([[1, 1], [1, 2]])

for x,y in d:
    print(x, y)

1 1
1 2


In [10]:
list1 = [1, 3, 5]
list2 = [2, 4, 6]
list1 + list2

[1, 3, 5, 2, 4, 6]

In [12]:
ndarray1 = np.array([1, 3, 5])
ndarray2 = np.array([2, 4, 6])
ndarray1 + ndarray2

array([ 3,  7, 11])

In [13]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [17]:
print(x.shape)
print(x.dtype)
print(x.ndim)
print(d.shape)
print(d.dtype)
print(d.ndim)
print(y/2.0)

(3,)
float64
1
(2, 2)
int32
2
[1. 2. 3.]


In [19]:
a = np.array([[1, 2], [3, 4], [5,6]])
print(a.ndim)

2


In [21]:
print(a.shape)

(3, 2)


In [25]:
np.dot(4, 2)



8

In [26]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
np.dot(array1, array2)


32

In [27]:

array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[1, 2], [3, 4]])
np.dot(array3, array4)


array([[ 7, 10],
       [15, 22]])

In [29]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])
np.matmul(array1, array2)

array([[ 7, 10],
       [15, 22]])

In [32]:
array3 = np.array([[1, 2]])
array4 = np.array([[1, 2], [3, 4]])
np.matmul(array3, array4)

array([[ 7, 10]])

In [36]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [38]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [39]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [41]:
ndarr.reshape(1,6)

array([[1, 2, 2, 3, 3, 4]])

In [43]:
np.random.randint(5, size=(2,4))

array([[2, 0, 1, 3],
       [0, 4, 3, 2]])

In [46]:
np.random.rand(2,4)

array([[0.12373006, 0.52722742, 0.60901118, 0.4640024 ],
       [0.47486819, 0.04204504, 0.40151598, 0.83409798]])

In [48]:
rng = np.random.default_rng()
rng.random()

0.9742011580769011

In [50]:
rng.integers(0, 10, (2,4))

array([[1, 2, 7, 1],
       [4, 2, 4, 9]], dtype=int64)

In [52]:
ndarr = np.array([[6, 3], [5, 2], [4, 1]])
ndarr > 4


array([[ True, False],
       [ True, False],
       [False, False]])

In [54]:
ndarr[ndarr > 4]

array([6, 5])