In [5]:
import numpy as np
x = np.array([3, 1, 2])
print(x)
print(type(x))
print(type([3, 1, 2]))

[3 1 2]
<class 'numpy.ndarray'>
<class 'list'>


In [9]:
c = [[1], [1,2]]
d = np.array([[1, 1], [1, 2]])

for x,y in d:
    print(x, y)

1 1
1 2


In [10]:
list1 = [1, 3, 5]
list2 = [2, 4, 6]
list1 + list2

[1, 3, 5, 2, 4, 6]

In [12]:
ndarray1 = np.array([1, 3, 5])
ndarray2 = np.array([2, 4, 6])
ndarray1 + ndarray2

array([ 3,  7, 11])

In [13]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [16]:
print(x.shape)
print(x.dtype)
print(x.ndim)
print(d.shape)
print(d.dtype)
print(d.ndim)
print(y/2.0)

(3,)
float64
1
(2, 2)
int32
2
[1. 2. 3.]
